### ISSUE TITLE
Building gdistribution from source. 

### ISSUE THREAD

**Issue by druvus** [bioinfo-ut/GenomeTester4#10]
It seems that gdistribution is not included in the current version of the Makefile. I would be greatful if you could update the file so it could be build from source as it is needed by StrainSeeker and PlasmidSeeker.

**Comment by bioinfo-ut** [comment]
Makefile and binaries were updated. Type 'make gdistribution' or download 64-bit binary from the bin/ folder.

**Comment by druvus** [comment]
Thanks for the updated bins but it seems that you forgot to add the updated makefile.

**Comment by bioinfo-ut** [comment]
Now everything should be fixed.
