### ISSUE TITLE
glistmaker error (4.0) or nothing (4.1) while outputting to nonexistent dir 

### ISSUE THREAD

**Issue by mihkelvaher** [bioinfo-ut/GenomeTester4#11]
`glistmaker my_fasta.fasta -w 16 -o not_existing_dir/outputList`
Version 4.0:
`Segmentation fault (core dumped)`

Version 4.1.1 (unstable)
Prints
`maker_queue_add_file: File testfasta.fasta as 1 blocks
  Block 0 from 0 to 24
Combined 1 arrays: input 1 (0.168 Mwords/s) output 1 (0.168 Mwords/s)
Combined 1 arrays: input 1 (0.200 Mwords/s) output 1 (0.200 Mwords/s)`
but outputs no file.

**Comment by lauris71** [comment]
Fixed in 4_1_unstable, now fails with error message
