### ISSUE TITLE
New release needed to update conda

### ISSUE THREAD

**Issue by CarolineOhrman** [bioinfo-ut/GenomeTester4#12]
Hi,
Could you make a new release so I can update the conda recepie to include gdistribution?
Thank you!

**Comment by bioinfo-ut** [comment]
We will try to make a new release, but it will take a few days.

**Comment by bioinfo-ut** [comment]
gdistribution is not supported as an independent binary any more.
The same functionality can be used by executing  
`glistquery -distribution MAX`

Do you need an official release for your conda recepie or can you use the code from branch 4_1_unstable ?
