### ISSUE TITLE
Use a temporary extension for work-in-progress lists

### ISSUE THREAD

**Issue by mihkelvaher** [bioinfo-ut/GenomeTester4#15]
**Problem:** If list creation is interrupted, there is no way to tell if the creation is finished or not.

**Possible solution:** Add a temporary extension to mark work in progress lists
For example, while creating a list the file is named `myList_32.list.tmp` and after it's finished, it is renamed to `myList_32.list`.

**Comment by lauris71** [comment]
Fixed in 4_1_unstable
