### ISSUE TITLE
gmer_counter not working with StrainSeeker

### ISSUE THREAD

**Issue by jiangweiyao** [bioinfo-ut/GenomeTester4#18]
Hi. I am trying to package GenomeTester4 and StrainSeeker into Bioconda packages for easier distribution. Since the gmer_counter and other binaries from StrainSeeker is from GenomeTester4, the build order was to compile the binaries from GenomeTester4 into a Bioconda package, and then build the StrainSeeker package using those binaries. Binaries are built from src code for transparency and reproducibility reasons. 

However, the gmer_counter from the GenomeTester4 repository (both the binary and the compiled from src files) don't work with StrainSeeker. I get the following error. Is it possible to get the source code and instructions that the GenomeTester4 binaries packaged with StrainSeeker was built from? Thank you.

```
jyao@Grayback:~/StrainSeeker/scripts$ /home/jyao/GenomeTester4-V4/bin/gmer_counter -dbb /home/jyao/Downloads/ss_db_w32_4324/db_binary --unique --distribution 1000 /home/jyao/Downloads/GCF_000008485.1_ASM848v1_genomic.fna
Cannot read binary database /home/jyao/Downloads/ss_db_w32_4324/db_binary
```

**Comment by lauris71** [comment]
Fixed in Version_4_0_stable
