### ISSUE TITLE
Cannot stat file Block 0 error?

### ISSUE THREAD

**Issue by milw** [bioinfo-ut/GenomeTester4#19]
Running the binary directly downloaded from the repository, and it does seem to generate an index- but there is a stat error for both of the blocks of input data...
```
/media/software/genometester4/4.0.0/bin/glistmaker /media/prod-data/genome-indexes/Wheat-IWGSC/chrTriticum_aestivum.IWGSC.dna.toplevel.fa -w 11 -o triticicum_aestivum_IWGSC1
maker_queue_add_file: File /media/prod-data/genome-indexes/Wheat-IWGSC/chrTriticum_aestivum.IWGSC.dna.toplevel.fa as 2 blocks
  Block 0 from 0 to 7755892916
Cannot stat file Block 0
  Block 1 from 7755892916 to 14789717255
Cannot stat file Block 1
```

**Comment by bioinfo-ut** [comment]
Thanks for the information. I believe the index will be functional despite the error codes.
You can also try a newer version of the GenomeTester4, version 4.1 is downloadable here: 
https://github.com/bioinfo-ut/GenomeTester4/tree/4_1_unstable
