### ISSUE TITLE
glistmaker unknown error

### ISSUE THREAD

**Issue by nadiabaig** [bioinfo-ut/GenomeTester4#28]
I am using glistmaker to generate kmer freq tables and ending up with the error message  Error: Program failed due to unknown reasons!.
Input files includes 10x based reads in fastq.gz format.

**Comment by MaidoRemm** [comment]
This means none of the other reasons for error were recognized. See the code within 'common.c'

If you want to know what is causing the problem in your case, you need to provide us the description of your hardware, software (Linux version), the exact command line you used, and your source data (Fastq file).

=========
	if (e == 1) {
		return 1;
	} else if (e == GT_INCOMPATIBLE_WORDLENGTH_ERROR) {
		fprintf (stderr, "Error: Incompatible wordlengths!\n");
		return 1;
	} else if (e == GT_OUT_OF_MEMORY_ERROR) {
		fprintf (stderr, "Error: Program out of memory!\n");
		return 1;
	} else if (e == GT_INCOMPATIBLE_VERSION_WARNING) {
		fprintf (stderr, "Warning: Two lists are built under different glistmaker versions!\n");
	} else if (e == GT_NEWER_VERSION_WARNING) {
		fprintf (stderr, "Warning: List is built under newer glistmaker version than your current program version!\n");
	} else if (e == GT_FASTA_START_SEQ_ERROR) {
		fprintf (stderr, "Error: Processing the start of the sequence failed!\n");
		return 1;
	} else if (e == GT_FASTA_END_SEQ_ERROR) {
		fprintf (stderr, "Error: Processing the end of the sequence failed!\n");
		return 1;
	} else if (e == GT_FASTA_PROCESS_SEQ_ERROR) {
		fprintf (stderr, "Error: Processing the sequence failed!\n");
		return 1;
	} else {
		fprintf (stderr, "Error: Program failed due to unknown reasons!\n");
		return 1;
	}

**Comment by nadiabaig** [comment]
Thanks.
I figured it out. The required amount of RAM to process this step was low.
Upgrading the systems computational power resulted in required output without errors.
