### ISSUE TITLE
no list file specified

### ISSUE THREAD

**Issue by ghost** [bioinfo-ut/GenomeTester4#3]
after creating a glist with the following command :
/glistmaker ../files/file.fasta -w 32 -o list_file

i've been trying to run the glistquery command, but it keeps telling me that no list was found even if i precised it in my command : 
glistquery -s ../files/file1.fastq -l ../list_file_32.txt -q AAAAAAGGCGAATACCCGCCTTATATGGTACTGGATTTTCCATTTCCGTAGAAAGATCGACATGTTGTAGTCAAACGTAAGTTGAGTAAAGCCAGTAATG -mm 1

ps: it's possible that my command isn't complete but i think it's weird that the program shows an error which isn't supposed to exsist... 
Do you have any suggestions ?

**Comment by lauris71** [comment]
Hello!

Thank you for trying out GenomeTester4!
For glistquery, the actual list (used as k-mer frequency database) 
should be specified without any arguments. The
arguments -l -q and -f specify the source from where k-mers are read. 
Only one of these should be specified.
So in your case the correct command-lines are:
glistquery list_file_32.txt -s ../files/file1.fastq
or
glistquery list_file_32.txt -q AAAAA...

I agree that it is bit confusing, so we'll make it more explicit in 
in-line help.

Best wishes,
Lauris Kaplinski

**Comment by ghost** [comment]
thanks i'll try this command ! 

It works fine, thank you !
