### ISSUE TITLE
FastGT segmentation fault with gzipped FASTQ input

### ISSUE THREAD

**Issue by jdidion** [bioinfo-ut/GenomeTester4#4]
Neither the documentation nor the inline help states what input file formats are allowed, but fastq is the most logical and (nearly) all modern bioinformatics tools support compressed input. However, the following command

~/GenomeTester4/bin/gmer_counter -db kmer_list_WG30238282.db --num_threads 1 foo.fastq.gz

results in a segmentation fault after (strangely) printing 5 lines of what looks like real output:

1:657698:rs565995692:C/T    6   0   0   0   0   0   0
1:658426:rs188842781:G/T    6   0   0   0   0   0   0
1:668346:rs115048193:G/A    6   0   0   0   0   0   0
1:668374:rs138476838:G/A    2   0   0
1:676127:rs150820983:C/T    6   0   0   0   0   0   0
Segmentation fault

Things seem to work when I uncompress the input file, but it would be much nicer if you could automatically detect and handle gzipped input files.

**Comment by jdidion** [comment]
This also results in a segmentation fault:

zcat *fastq.gz | gmer_counter -db kmer_list_WG30238282.db --num_threads 16 - > gmer_counts.txt

When I try using only a subset of reads it works, so it must be a problem with the volume of input. It's not running out of memory - I give it 32G and it only uses 4G before it dies.

**Comment by warthmann** [comment]
I have the same problem. doesn't work on compressed files, seems to work on uncompressed, but could not find a way to pipe it through

**Comment by lauris71** [comment]
Detection and reading gzipped files is now supported in 4_1_unstable branch.
