### ISSUE TITLE
Support for compressed datatset.

### ISSUE THREAD

**Issue by taranglute** [bioinfo-ut/GenomeTester4#7]
Hi
I have quick query and it is related to support for compressed datatset.
Does GenomeTester4 supports compressed datatset(gzip) as I am not sure.

Regards

**Comment by bioinfo-ut** [comment]
No, it does not. You need to unpack gzip file first.

If you use glistmaker or gmer_counter from this package, then I would also suggest to split FASTQ  file(s) to ca 10 equal pieces, this speeds up the k-mer counting significantly. For example
cat file1.fastq file2.fastq | split -l 300000000

**Comment by taranglute** [comment]
Thanks :+1:
